version: '3.3'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=24EN4SPVSrTdyjS4hYrx
      - MYSQL_PASSWORD=SD7Xdf393wjkohYS264K
      - MYSQL_USER=root
      - MYSQL_DATABASE=multichoice
